{{- if .Values.esocial.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esocial
  generation: 1
  labels:
    io.kompose.service: esocial
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: esocial
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        io.kompose.service: esocial
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: monitoring
                operator: NotIn
                values:
                - "true"
      containers:
      - args:
        - sudo java -jar /home/mgeweb/DSEM/docker-sanesocial-manager.jar && sleep 5 &&
          /home/mgeweb/DSEM/scripts/./run-sanesocial.sh && sleep 15 && /home/mgeweb/sanesocial/./sanesocial-service
          start && sleep 15 && nohup /home/mgeweb/DSEM/scripts/./sentry  2>&1 </dev/null
          & sleep 15 && echo 'y' && sleep 15 && tail -f /home/mgeweb/sanesocial/log/server.log
        command:
        - /bin/sh
        - -c
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "{{ .Values.jboss.envs }}"
        - name: APP
          value: esocial
        - name: CLIENTE
          value: "{{ .Release.Namespace }}"
        - name: PATH_LOG
          value: /home/mgeweb/sanesocial/log/server.log
        image: {{  .Values.imageRepository.esocial.image }}:{{  .Values.imageRepository.esocial.imageTag }}
        imagePullPolicy: IfNotPresent
        name: esocial
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 40
          periodSeconds: 40
          successThreshold: 1
          tcpSocket:
            port: 8778
          timeoutSeconds: 40
        ports:
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 40
          periodSeconds: 40
          successThreshold: 1
          tcpSocket:
            port: 8778
          timeoutSeconds: 40
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
        volumeMounts:
        - mountPath: /home/mgeweb/sanesocial/conf
          name: volume-conf
        - mountPath: /home/mgeweb/sanesocial/certificados
          name: volume-certificados
        - mountPath: /home/mgeweb/sanesocial/properties
          name: volume-properties
        - mountPath: /home/mgeweb/versoes
          name: volume-pacotesocial
      dnsConfig:
        nameservers:
        {{- range .Values.dns.nameservers }}
          - {{ . | title | quote }}
        {{- end }}  
        options:
        - name: ndots
          value: "15"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: volume-conf
        hostPath: 
          path: {{ .Values.volume.pathDefault }}{{ .Release.Name }}/esocial/conf/
          type: DirectoryOrCreate
      - name: volume-certificados
        hostPath: 
          path: {{ .Values.volume.pathDefault }}{{ .Release.Name }}/esocial/certificados/
          type: DirectoryOrCreate
      - name: volume-properties
        hostPath: 
          path: {{ .Values.volume.pathDefault }}{{ .Release.Name }}/esocial/properties/
          type: DirectoryOrCreate
      - name: volume-pacotesocial
        hostPath: 
          path: {{ .Values.volume.pathDefault }}pacotesocial/
          type: DirectoryOrCreate
status: {}
{{- end }}
