apiVersion: v1
kind: Secret
metadata: 
  name: sankhya-w
type: Opaque
data:
  banco-password: "{{ .Values.banco.senha | b64enc }}"
  banco-user: "{{ .Values.banco.usuario | b64enc  }}"
  {{- if eq .Values.banco.alias "outro..." }}
  banco-ip: "{{ .Values.banco.ip | b64enc }}"
  {{- else if eq .Values.banco.alias "dboci2" }}
  banco-ip: "{{ .Values.bancos_existentes.dboci2 | b64enc }}"
  {{- else if eq .Values.banco.alias "oci5" }}
  banco-ip: "{{ .Values.bancos_existentes.oci5 | b64enc }}"
  {{- else if eq .Values.banco.alias "oci6" }}
  banco-ip: "{{ .Values.bancos_existentes.oci6 | b64enc }}"
  {{- else }}
  banco-ip: "{{ .Values.bancos_existentes.dbocit1 | b64enc }}"
  {{- end }}