description: Jiva-W
icon: https://s3-sa-east-1.amazonaws.com/jiva-docker/rancher2/catalogIcon-jiva-w.png
home: https://www.jiva.com.br
name: jiva-w
version: 2.7
maintainers:
  - email: highlander.dantas@sankhya.com.br
    name: Highlander Dantas
  - email: daniel.silva@sankhya.com.br
    name: Daniel Marques
